### PR TITLE
Multithreading

### PR DESCRIPTION
**Pull request by cab404**
Also I threw in fixes for Python 3.8 warnings and less cluttered logging

That increases speed significantly on any multicore system.

### CODE REVIEW

**Comment by cab404** [comment]
@fookatchu ?

**Comment by fookatchu** [comment]
everything looks good, but i need to test the code before merging, as there are quite a few changes. give me a few days!

**Comment by cab404** [comment]
> everything looks good, but i need to test the code before merging, as there are quite a few changes. give me a few days!

thanks)

**Comment by cab404** [comment]
on the side note — I packaged your converter into nixpkgs)

**Comment by cab404** [comment]
up

**Comment by cab404** [comment]
I am closing this for now, cause I started pushing into my master. Probably will re-pull either everything, or branch-by-branch

**Pull request closed without merging**
